---
heat_template_version: 2016-04-08

# **********************************************************************************************************************
# TODO: Change how we iterate through ResourceGroup items when moving templates to Ocata version.
# There is a bug in repeat function that is only fixed in Ocata release. https://bugs.launchpad.net/heat/+bug/1629899
# So we're not able to use get_attr in the for_each, as shown below:
# repeat:
#   template:
#     port: <%port%>
#   for_each:
#     <%port%>: { get_attr: [bigip_nnic_handler, port_ids] }
# We can't use OS::Heat::Value as well, as it is only supported in Newton.
# As a workaround, we turn the list into a string, then split again, to force repeat function to recognize the list.
# **********************************************************************************************************************

description: This template deploys a standard f5 standalone BIG-IP VE with dynamic number of NICs.

parameters:
  bigip_image:
    type: string
    label: f5 BIG-IP VE Image
    description: The BIG-IP VE image to be used on the compute instance.
    constraints:
      - custom_constraint: glance.image
  bigip_flavor:
    type: string
    label: f5 BIG-IP VE Flavor
    description: Type of instance (flavor) to be used for the VE.
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor
  use_config_drive:
    type: boolean
    label: Use Config Drive
    description: Use config drive to provide meta and user data.
    default: false
  f5_cloudlibs_tag:
    type: string
    label: f5 CloudLibs Tag
    description: Tag that determines version of f5 cloudlibs to use for provisioning. If specified, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value.
    default: v3.5.0
  f5_cloudlibs_url_override:
    type: string
    label: f5 cloud-libs URL Override
    description: Alternate URL for f5-cloud-libs package. If not specified, the default GitHub location for f5-cloud-libs will be used. If version is different from default f5_cloudlibs_tag, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value. If version is different from default f5_cloudlibs_tag, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value.
    default: None
  f5_cloudlibs_verify_hash_url_override:
    type: string
    label: f5 cloud-libs verifyHash URL Override
    description: Alternate URL for verifyHash used to validate f5-cloud-libs package. If not specified, the scripts/verifyHash will be used.
    default: None
  f5_cloudlibs_openstack_tag:
    type: string
    label: f5-cloud-libs-openstack Tag
    description: Tag that determines version of f5 cloudlibs-package to use for provisioning. If specified, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value.
    default: v1.0.0
  f5_cloudlibs_openstack_url_override:
    type: string
    label: f5-cloud-libs-openstack URL Override
    description: Alternate URL for f5-cloud-libs-openstack package. If not specified, the default GitHub location for f5-cloud-libs will be used. If version is different from default f5_cloudlibs_tag, ensure that hashes are valid by either updating scripts/verifyHash or by providing a f5_cloudlibs_verify_hash_url_override value.
    default: None    
  bigip_servers_ntp:
    type: comma_delimited_list
    label: f5 BIG-IP VE NTP servers
    description: A list of NTP servers to configure on the BIG-IP.
    default:
      - 0.us.pool.ntp.org
      - 1.us.pool.ntp.org
  bigip_servers_dns:
    type: comma_delimited_list
    label: f5 BIG-IP VE Domain Name Servers
    description: A list of DNS servers to configure on the BIG-IP.
    default:
      -
  allow_usage_analytics:
    type: boolean
    label: Allow Usage Analytics
    description: Toggles whether non-identifiable statistical information is sent to F5.
    default: true

  # bigip nnic provisioning
  bigip_nic_count:
    type: number
    label: f5 BIG-IP NIC count
    description: Number of additional NICs to attach to the BIG-IP. Note - exclude management nic from count.
    constraints:
      - range: {min: 1, max: 10}

  # bigip credentials
  bigip_os_ssh_key:
    type: string
    label: f5 BIG-IP VE Root SSH Key Name
    description: Name of key-pair to be installed on the BIG-IP VE instance to allow root SSH access.
    constraints:
      - custom_constraint: nova.keypair
  bigip_admin_pwd:
    type: string
    label: f5 BIG-IP VE Admin User Password
    description: Password for the BIG-IP admin user.
    hidden: true
  bigip_root_pwd:
    type: string
    label: f5 BIG-IP VE Root User Password
    description: Password for the BIG-IP root user.
    hidden: true

  # bigip licensing
  bigip_license_key:
    type: string
    label: Primary BIG-IP VE License Base Key
    description: f5 BIG-IP License Base Key.
    default: None
  bigip_addon_license_keys:
    type: comma_delimited_list
    label: Additional BIG-IP VE License Keys
    description: f5 BIG-IP License Add-On Keys.
    default:
      -
  bigip_modules:
    type: comma_delimited_list
    label: Modules to provision on the BIG-IP.
    description: A list modules to provision and their level. <module_name:level>
    default:
      - ltm:nominal

  # os network
  external_network:
    type: string
    label: External Network Name
    description: Name of external network where floating IP resides.
    constraints:
      - custom_constraint: neutron.network
  mgmt_network:
    type: string
    label: Management Network
    description: Network to which the BIG-IP management interface is attached.
    constraints:
      - custom_constraint: neutron.network
  mgmt_mtu:
    type: number
    label: Management Interface MTU
    description: Network MTU for the BIG-IP management interface.
    default: 1400
  mgmt_security_group_name:
    type: string
    label: Management Security Group Name
    description: Name to apply on the security group for the BIG-IP management network.
  network_vlan_security_group_rules:
    type: json
    label: Security Group Rules
    description: The rules to apply to the security group
  network_vlan_names:
    type: comma_delimited_list
    label: OS Neutron Network to map to the BIG-IP VLAN
    description: The Neutron Networks for the corresponding BIG-IP VLANs.
    constraints:
  network_vlan_subnets:
    type: comma_delimited_list
    label: OS Neutron Subnet to map to the BIG-IP VLAN
    description: The Neutron Subnet for the corresponding BIG-IP VLANs.
    constraints:

  # bigip network
  bigip_default_gateway:
    type: string
    label: Default Gateway IP
    description: Upstream Gateway IP Address for BIG-IP instance.
    default: None
  bigip_mgmt_port:
    type: number
    label: Management port
    description: Port for the BIG-IP Management uri
    default: 443
  bigip_vlan_names:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN names
    description: Names of the VLAN to be created on the BIG-IP.
    default:
      -
  bigip_vlan_mtus:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN MTUs
    description: MTU value of the VLAN on the BIG-IP.
  bigip_vlan_tags:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN tags
    description: Tags to apply on the VLAN on the BIG-IP. Use default value "None" for untagged.
    default: None
  bigip_self_port_lockdowns:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN Allow Services
    description: Optional list with each item a list of <service:port> lockdown settings for the VLAN. If no value is supplied, default is used. Each list item corresponds to the settings for each NIC at that index.
    default:
      -
  f5_bigiq_host:
    type: string
    label: BigIQ Host
    description: BigIQ license activation host.
    default: 192.168.245.1
  f5_bigiq_username:
    type: string
    label: BigIQ Username
    description: BigIQ license user.
    default: admin
  f5_bigiq_password:
    type: string
    label: BigIQ Password
    description: BigIQ license user.
    default: admin
    hidden: true
  f5_bigiq_license_pool_name:
    type: string
    label: BigIQ License Pool Name
    description: BigIQ license pool to use for this VE

parameter_groups:
  - label: BIG-IP General Provisioning
    parameters:
      - bigip_image
      - bigip_flavor
      - use_config_drive
      - f5_cloudlibs_tag
      - f5_cloudlibs_url_override
      - f5_cloudlibs_verify_hash_url_override
      - f5_cloudlibs_openstack_tag
      - f5_cloudlibs_openstack_url_override
      - bigip_servers_ntp
      - bigip_servers_dns
      - allow_usage_analytics
  - label: BIG-IP nNIC Provisioning
    parameters:
      - bigip_nic_count
  - label: BIG-IP Credentials
    parameters:
      - bigip_os_ssh_key
      - bigip_admin_pwd
      - bigip_root_pwd
  - label: BIG-IP Licensing and Modules
    parameters:
      - bigip_license_key
      - bigip_addon_license_keys
      - bigip_modules
  - label: OS Network
    parameters:
      - external_network
      - mgmt_network
      - mgmt_mtu
      - mgmt_security_group_name
      - network_vlan_security_group_rules
      - network_vlan_names
      - network_vlan_subnets
  - label: BIG-IP Network
    parameters:
      - bigip_default_gateway
      - bigip_mgmt_port
      - bigip_vlan_names
      - bigip_vlan_mtus
      - bigip_vlan_tags
      - bigip_self_port_lockdowns
  - label: Licensing
    parameters:
      - f5_bigiq_host
      - f5_bigiq_username
      - f5_bigiq_password
      - f5_bigiq_license_pool_name

resources:

  bigip_instance:
    type: F5::BigIP::Standalone
    properties:
      bigip_image: {get_param: bigip_image}
      bigip_flavor: {get_param: bigip_flavor}
      use_config_drive: {get_param: use_config_drive}
      f5_cloudlibs_tag: {get_param: f5_cloudlibs_tag}
      f5_cloudlibs_url_override: {get_param: f5_cloudlibs_url_override}
      f5_cloudlibs_verify_hash_url_override: {get_param: f5_cloudlibs_verify_hash_url_override}
      f5_cloudlibs_openstack_tag: {get_param: f5_cloudlibs_openstack_tag}
      f5_cloudlibs_openstack_url_override: {get_param: f5_cloudlibs_openstack_url_override}
      bigip_servers_ntp: {get_param: bigip_servers_ntp}
      bigip_servers_dns: {get_param: bigip_servers_dns}
      allow_usage_analytics: {get_param: allow_usage_analytics}
      bigip_nic_count: {get_param: bigip_nic_count}
      bigip_os_ssh_key: {get_param: bigip_os_ssh_key}
      bigip_admin_pwd: {get_param: bigip_admin_pwd}
      bigip_root_pwd: {get_param: bigip_root_pwd}
      bigip_license_key: {get_param: bigip_license_key}
      bigip_addon_license_keys: {get_param: bigip_addon_license_keys}
      bigip_modules: {get_param: bigip_modules}
      external_network: {get_param: external_network}
      mgmt_network: {get_param: mgmt_network}
      mgmt_mtu: {get_param: mgmt_mtu}
      mgmt_security_group_name: {get_param: mgmt_security_group_name}
      network_vlan_security_group_rules: {get_param: network_vlan_security_group_rules}
      network_vlan_names: {get_param: network_vlan_names}
      network_vlan_subnets: {get_param: network_vlan_subnets}
      bigip_default_gateway: {get_param: bigip_default_gateway}
      bigip_mgmt_port: {get_param: bigip_mgmt_port}
      bigip_vlan_names: {get_param: bigip_vlan_names}
      bigip_vlan_mtus: {get_param: bigip_vlan_mtus}
      bigip_vlan_tags: {get_param: bigip_vlan_tags}
      bigip_self_port_lockdowns: {get_param: bigip_self_port_lockdowns}

  bigip_licensor:
    type: F5::BigIQ::RegKeyPoolLicensor
    depends_on: [bigip_instance]
    properties:
      bigiq_host: {get_param: f5_bigiq_host}
      bigiq_username: {get_param: f5_bigiq_username}
      bigiq_password: {get_param: f5_bigiq_password}
      bigiq_license_pool_name: {get_param: f5_bigiq_license_pool_name}
      bigip_management_ip: {get_attr: [bigip_instance, floating_ip]}
      bigip_username: admin
      bigip_password: {get_param: bigip_admin_pwd}

outputs:
  bigip_instance_id:
    description: ID of the BIG-IP instance
    value: {get_attr: [bigip_instance, bigip_instance_id]}
  bigip_instance_name:
    description: Name of the BIG-IP instance
    value: {get_attr: [bigip_instance, bigip_instance_name]}
  floating_ip:
    description: The Floating IP address of the BIG-IP instance
    value: {get_attr: [bigip_instance, floating_ip]}
  mgmt_ip:
    description: The mgmt IP address of BIG-IP instance
    value: {get_attr: [bigip_instance, mgmt_ip]}
  mgmt_mac:
    description: The mgmt MAC address of BIG-IP instance
    value: {get_attr: [bigip_instance, mgmt_mac]}
  mgmt_port_id:
    description: The port id of the BIG-IP mgmt interface
    value: {get_attr: [bigip_instance, mgmt_port_id]}
  data_port_ids:
    description: The port ids of the TMM interfaces
    value: {get_attr: [bigip_instance, data_port_ids]}
  data_fixed_ips:
    description: The fixed_ips for the port of the TMM interfaces
    value: {get_attr: [bigip_instance, data_fixed_ips]}
  data_fixed_subnets:
    description: The port ids of the TMM interfaces
    value: {get_attr: [bigip_instance, data_fixed_subnets]}
  
