heat_template_version: 2016-04-08

description: This template configures clustering components for a standard f5 VE image in a config-sync cluster.

resources:
  onboard_cluster_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        write_files:
          - path: /config/onboard-cluster.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/onboard-cluster.sh}

outputs:
  OS::stack_id:
    description: F5::BigIP::OnboardClusterConfig resource.
    value:
      get_resource: onboard_cluster_config
