heat_template_version: 2016-04-08

description: This template configures network components for a standard f5 standalone VE image.

resources:
  onboard_network_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        write_files:
          - path: /config/onboard-network.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/onboard-network-nnic.sh}

outputs:
  OS::stack_id:
    description: The F5::BigIP::OnboardNetworkConfigNNic resource.
    value:
      get_resource:  onboard_network_config
