heat_template_version: 2016-04-08

description: This template creates additional scripts required to provision a Big-IP.

resources:
  onboarding_scripts:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        write_files:
          - path: /config/verifyHash
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/verifyHash }
          - path: /config/preOnboard.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/preOnboard.sh }
          - path: /config/wait-cloudlibsInstall.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/wait-cloudlibsInstall.sh }
          - path: /config/postOnboard.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/postOnboard.sh }
          - path: /config/onboard.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/onboard.sh }

outputs:
  OS::stack_id:
    description: The F5::BigIP::OnboardingScripts resource.
    value:
      get_resource: onboarding_scripts
