heat_template_version: 2016-04-08

description: This template downloads additional packages required to provision a Big-IP.

resources:
  onboarding_cloudlibs:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        write_files:
          - path: /config/wait-cloudlibsDownload.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/wait-cloudlibsDownload.sh }
          - path: /config/download-cloudlibs.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/download-cloudlibs.sh }

outputs:
  OS::stack_id:
    description: The F5::BigIP::OnboardingScripts resource.
    value:
      get_resource: onboarding_cloudlibs
