heat_template_version: 2016-04-08

description: This template performs overrides of defaults for a standard f5 standalone VE image.

resources:
  override_default_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        { get_file: ../scripts/onboard-defaultConfig.sh }
outputs:
  OS::stack_id:
    description: F5::BigIP::OverrideDefaultConfig resource.
    value:
      get_resource: override_default_config

