heat_template_version: 2016-04-08

description: This template contains static management nic config for a standard f5 standalone VE image.

resources:
  static_mgmt_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        write_files:
          - path: /config/setup-staticMgmt.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/setup-staticMgmt.sh }
          - path: /config/wait-staticMgmtConfig.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/wait-staticMgmtConfig.sh }
        bootcmd:
          - echo '******BOOT COMMAND START*******'
          - /usr/bin/setdb dhclient.mgmt disable && echo '*** disabled dhclient'
          - echo '******BOOT COMMAND END*******'

outputs:
  OS::stack_id:
    description: F5::BigIP::StaticMgmtConfig resource.
    value:
      get_resource: static_mgmt_config
