---
heat_template_version: 2016-04-08

description: This template builds components for dynamic number of nics.

parameters:
  bigip_nic_count:
    type: number
    label: f5 BIG-IP NIC count
    description: Number of additional NICs to attach to the BIG-IP. Note - exclude management nic from count.
  network_vlan_names:
    type: comma_delimited_list
    label: OS Neutron Network to map to the BIG-IP VLAN
    description: The Neutron Network for the corresponding BIG-IP VLAN.
  network_vlan_subnets:
    type: comma_delimited_list
    label: OS Neutron Subnet to map to the BIG-IP VLAN
    description: The Neutron Subnet for the corresponding BIG-IP VLAN.
  network_vlan_security_group_rules:
    type: json
    label: Security Group Rules
    description: The rules to apply to the security group
  bigip_default_gateway:
    type: string
    label: Default Gateway IP
    description: Upstream Gateway IP Address for BIG-IP instance.
    default: None
  bigip_vlan_names:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN name
    description: Name of the VLAN to be created on the BIG-IP.
    default:
      -
  bigip_vlan_mtus:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN MTU
    description: MTU value of the VLAN on the BIG-IP.
  bigip_vlan_tags:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN tag
    description: Tag to apply on the VLAN on the BIG-IP. Use default value "None" for untagged.
    default: None
  bigip_self_port_lockdowns:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN Allow Services
    description: Optional list of <service:port> lockdown settings for the VLAN. If no value is supplied, default is used.
    default:

resources:

  security_groups:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: bigip_nic_count}
      resource_def:
        type: F5::BigIP::CustomSecurityGroup
        properties:
          network_vlan_names: {get_param: network_vlan_names}
          security_group_index: "%index%"
          security_group_rules: {get_param: [network_vlan_security_group_rules, security_group_rules]}

  network_vlan_ports:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: bigip_nic_count}
      resource_def:
        type: F5::BigIP::NeutronPortSingleFixedIP
        properties:
          index: "%index%"
          network_names: {get_param: network_vlan_names}
          network_subnets: {get_param: network_vlan_subnets}
          security_groups: {get_attr: [security_groups, security_group_id]}
          
outputs:
  port_ids:
    value: {get_attr: [network_vlan_ports, neutron_port_id]}
  port_fixed_ips:
    value: {get_attr: [network_vlan_ports, neutron_port_fixed_ips]}
  port_subnets:
    value: {get_attr: [network_vlan_ports, neutron_port_subnets]}
  bigip_selfips:
    value: {get_attr: [network_vlan_ports, bigip_selfip_address]}
  bigip_selfip_cidrs:
    value: {get_attr: [network_vlan_ports, bigip_selfip_cidr]}
  bigip_selfip_masks:
    value: {get_attr: [network_vlan_ports, bigip_selfip_mask]}
  bigip_selfip_gateway:
    value: {get_attr: [network_vlan_ports, bigip_selfip_gateway]}
